#!/usr/bin/env python3
"""Fetch JPL SBDB orbital + physical elements for the curated bundled set of
famous asteroids and comets, emit BundledSmallBodies.java.

The bundled list is intentionally small — users download additional bodies
through the in-app download feature. This script can be re-run to refresh
elements when MPC publishes updates.
"""

import json
import ssl
import urllib.parse
import urllib.request
from pathlib import Path

try:
    import certifi
    _SSL_CONTEXT = ssl.create_default_context(cafile=certifi.where())
except ImportError:
    _SSL_CONTEXT = ssl.create_default_context()

PROJECT_ROOT = Path(__file__).resolve().parent.parent
OUT_FILE = (
    PROJECT_ROOT
    / "app" / "src" / "main" / "java" / "com" / "example" / "onstepcontroller"
    / "BundledSmallBodies.java"
)
SBDB_API = "https://ssd-api.jpl.nasa.gov/sbdb.api"

# Curated list. Each entry: (sstr_query, display_name_zh, display_name_en, kind)
# kind = "asteroid" | "comet". The query string is what JPL SBDB accepts —
# numbered asteroids by integer, comets by IAU designation like "1P".
ASTEROIDS = [
    ("1",      "谷神星",     "Ceres"),
    ("2",      "智神星",     "Pallas"),
    ("3",      "婚神星",     "Juno"),
    ("4",      "灶神星",     "Vesta"),
    ("6",      "韶神星",     "Hebe"),
    ("7",      "虹神星",     "Iris"),
    ("8",      "花神星",     "Flora"),
    ("9",      "海女星",     "Metis"),
    ("10",     "健神星",     "Hygiea"),
    ("11",     "海妖星",     "Parthenope"),
    ("15",     "和神星",     "Eunomia"),
    ("433",    "爱神星",     "Eros"),
]

COMETS = [
    ("1P",     "哈雷彗星",                "1P/Halley"),
    ("2P",     "恩克彗星",                "2P/Encke"),
    ("9P",     "坦普尔1号彗星",           "9P/Tempel 1"),
    ("67P",    "丘留莫夫-格拉西缅科彗星", "67P/Churyumov-Gerasimenko"),
    ("109P",   "斯威夫特-塔特尔彗星",     "109P/Swift-Tuttle"),
]


def fetch(query: str) -> dict:
    params = urllib.parse.urlencode({"sstr": query, "phys-par": "true", "full-prec": "true"})
    url = f"{SBDB_API}?{params}"
    with urllib.request.urlopen(url, timeout=60, context=_SSL_CONTEXT) as r:
        return json.loads(r.read().decode("utf-8"))


def value_of(items, name, fallback=None):
    for entry in items:
        if entry.get("name") == name:
            try:
                return float(entry["value"])
            except (TypeError, ValueError):
                return fallback
    return fallback


def parse_record(query, name_zh, name_en, payload, is_comet):
    elements = payload["orbit"]["elements"]
    epoch = float(payload["orbit"]["epoch"])
    e = value_of(elements, "e")
    a = value_of(elements, "a")
    q = value_of(elements, "q")
    i = value_of(elements, "i")
    om = value_of(elements, "om")
    w = value_of(elements, "w")
    tp = value_of(elements, "tp")
    if q is None and a is not None and e is not None:
        q = a * (1.0 - e)
    if a is None and q is not None and e is not None and e < 1.0:
        a = q / (1.0 - e)

    phys = payload.get("phys_par") or []
    if is_comet:
        H = value_of(phys, "M1", fallback=value_of(phys, "M2", fallback=15.0))
        slope = value_of(phys, "K1", fallback=value_of(phys, "K2", fallback=10.0))
    else:
        H = value_of(phys, "H", fallback=15.0)
        slope = value_of(phys, "G", fallback=0.15)

    designation = payload["object"].get("des", query).strip()
    return {
        "designation": designation,
        "name_zh": name_zh,
        "name_en": name_en,
        "is_comet": is_comet,
        "epoch_jd": epoch,
        "q_au": q,
        "e": e,
        "i_deg": i,
        "om_deg": om,
        "w_deg": w,
        "tp_jd": tp,
        "magnitude": H,
        "slope": slope,
    }


def fmt(v):
    if v is None:
        return "Double.NaN"
    return repr(float(v))


def emit(records):
    lines = [
        "package com.example.onstepcontroller;",
        "",
        "// AUTO-GENERATED by scripts/generate-bundled-small-bodies.py.",
        "// Source: JPL Small-Body Database (https://ssd-api.jpl.nasa.gov/sbdb.api).",
        "// Re-run the generator to refresh bundled elements.",
        "",
        "import java.util.Arrays;",
        "import java.util.List;",
        "",
        "final class BundledSmallBodies {",
        "    private BundledSmallBodies() {}",
        "",
        "    static List<SmallBody> all() {",
        "        return Arrays.asList(",
    ]
    for r in records:
        kind = "true" if r["is_comet"] else "false"
        lines.append(
            "            new SmallBody("
            f"\"{r['designation']}\", "
            f"\"{r['name_zh']}\", "
            f"\"{r['name_en']}\", "
            f"{kind}, "
            f"{fmt(r['epoch_jd'])}, "
            f"{fmt(r['q_au'])}, "
            f"{fmt(r['e'])}, "
            f"{fmt(r['i_deg'])}, "
            f"{fmt(r['om_deg'])}, "
            f"{fmt(r['w_deg'])}, "
            f"{fmt(r['tp_jd'])}, "
            f"{fmt(r['magnitude'])}, "
            f"{fmt(r['slope'])})"
            + ("," if r is not records[-1] else "")
        )
    lines.extend([
        "        );",
        "    }",
        "}",
        "",
    ])
    OUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUT_FILE.write_text("\n".join(lines), encoding="utf-8", newline="\n")


def main():
    records = []
    for query, zh, en in ASTEROIDS:
        print(f"  fetching asteroid {query} ({en}) ...")
        payload = fetch(query)
        records.append(parse_record(query, zh, en, payload, is_comet=False))
    for query, zh, en in COMETS:
        print(f"  fetching comet {query} ({en}) ...")
        payload = fetch(query)
        records.append(parse_record(query, zh, en, payload, is_comet=True))
    emit(records)
    print(f"Wrote {OUT_FILE} with {len(records)} bodies")


if __name__ == "__main__":
    main()
