#!/usr/bin/env python3
"""Generate Vsop87Tables.java from IMCCE VSOP87D data files.

VSOP87D variant: heliocentric spherical (L longitude, B latitude, R radius)
referred to the dynamical ecliptic and equinox of the date.

The script downloads each planet's data file once into scripts/data/vsop87/,
parses every series, drops terms below an amplitude threshold, and writes a
single Java source file at:
    app/src/main/java/com/example/onstepcontroller/Vsop87Tables.java

Each retained term is stored as {A, B, C}; its contribution to the variable
is A * cos(B + C * tau), where tau is millennia from J2000 TT:
    tau = (JD - 2451545.0) / 365250.0
"""

import math
import ssl
import urllib.request
from pathlib import Path

try:
    import certifi
    _SSL_CONTEXT = ssl.create_default_context(cafile=certifi.where())
except ImportError:
    _SSL_CONTEXT = ssl.create_default_context()

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = PROJECT_ROOT / "scripts" / "data" / "vsop87"
OUT_FILE = (
    PROJECT_ROOT
    / "app" / "src" / "main" / "java" / "com" / "example" / "onstepcontroller"
    / "Vsop87Tables.java"
)

BASE_URL = "https://ftp.imcce.fr/pub/ephem/planets/vsop87/"

PLANETS = [
    ("MERCURY", "VSOP87D.mer"),
    ("VENUS",   "VSOP87D.ven"),
    ("EARTH",   "VSOP87D.ear"),
    ("MARS",    "VSOP87D.mar"),
    ("JUPITER", "VSOP87D.jup"),
    ("SATURN",  "VSOP87D.sat"),
    ("URANUS",  "VSOP87D.ura"),
    ("NEPTUNE", "VSOP87D.nep"),
]

# Amplitude truncation thresholds. VSOP87D L/B are in radians; R is in AU.
# 1e-6 rad ≈ 0.2 arcsec, so THRESHOLD_LB = 1e-6 keeps the leading-order
# contribution under control for ~1″ overall precision after summing.
THRESHOLD_LB = 1e-6
THRESHOLD_R = 1e-7


def download(filename: str) -> Path:
    target = DATA_DIR / filename
    if target.exists():
        return target
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    url = BASE_URL + filename
    print(f"  downloading {filename} ...")
    with urllib.request.urlopen(url, timeout=120, context=_SSL_CONTEXT) as r:
        target.write_bytes(r.read())
    return target


def parse_file(path: Path):
    """Yield (variable_letter, power, [(A, B, C), ...]) per series."""
    series = None
    var = None
    power = None
    with open(path, "r", encoding="ascii") as f:
        for line in f:
            if " VSOP87" in line and "VARIABLE" in line:
                if series is not None:
                    yield var, power, series
                idx = int(line.split("VARIABLE")[1].strip()[0])
                var = "LBR"[idx - 1]
                t_pos = line.index("*T**")
                power = int(line[t_pos + 4: t_pos + 5])
                series = []
            else:
                if series is None:
                    continue
                if len(line) < 131:
                    continue
                try:
                    A = float(line[79:97])
                    B = float(line[97:111])
                    C = float(line[111:131])
                except ValueError:
                    continue
                series.append((A, B, C))
    if series is not None:
        yield var, power, series


def truncate(var: str, terms):
    threshold = THRESHOLD_R if var == "R" else THRESHOLD_LB
    return [(A, B, C) for (A, B, C) in terms if abs(A) >= threshold]


def fmt_double(value: float) -> str:
    # Use 11-significant-digit scientific to match VSOP87 precision and keep
    # source line widths predictable.
    if value == 0.0:
        return "0.0"
    return f"{value:.11e}"


def emit_java(planets_data) -> int:
    lines = [
        "package com.example.onstepcontroller;",
        "",
        "// AUTO-GENERATED by scripts/generate-vsop87.py from IMCCE VSOP87D data.",
        "// Do not edit by hand; re-run the generator to refresh.",
        "// Each entry is {A, B, C}; contribution = A * cos(B + C * tau).",
        "// tau = (JD - 2451545.0) / 365250.0 (millennia from J2000 TT).",
        "",
        "final class Vsop87Tables {",
        "    private Vsop87Tables() {}",
        "",
    ]
    total_terms = 0
    # Each non-empty array is initialised by its own private loader method so
    # that no single Java method (including <clinit>) exceeds the 64 KiB JVM
    # bytecode limit when totalling thousands of VSOP87 terms.
    loader_methods = []
    for planet, variables in planets_data.items():
        for var in "LBR":
            powers = variables.get(var, {})
            for power in range(6):
                field = f"{planet}_{var}{power}"
                loader = f"load_{field}"
                terms = powers.get(power, [])
                if not terms:
                    lines.append(f"    static final double[][] {field} = new double[0][];")
                    continue
                total_terms += len(terms)
                lines.append(f"    static final double[][] {field} = {loader}();")
                loader_methods.append((loader, terms))
            lines.append("")
    for loader, terms in loader_methods:
        lines.append(f"    private static double[][] {loader}() {{")
        lines.append("        return new double[][]{")
        for A, B, C in terms:
            lines.append(
                f"            {{{fmt_double(A)}, {fmt_double(B)}, {fmt_double(C)}}},"
            )
        lines.append("        };")
        lines.append("    }")
        lines.append("")

    # Emit a coordinates() helper that returns {L, B, R} for a planet at tau.
    lines.extend([
        "    static double[] coordinates(SolarSystemEphemeris.Planet planet, double tau) {",
        "        switch (planet) {",
    ])
    for planet, _ in PLANETS:
        if planet == "EARTH":
            continue  # Earth handled via EARTH constants directly when needed
        lines.append(f"            case {planet}:")
        lines.append(
            f"                return computeLBR("
            f"{planet}_L0, {planet}_L1, {planet}_L2, {planet}_L3, {planet}_L4, {planet}_L5, "
            f"{planet}_B0, {planet}_B1, {planet}_B2, {planet}_B3, {planet}_B4, {planet}_B5, "
            f"{planet}_R0, {planet}_R1, {planet}_R2, {planet}_R3, {planet}_R4, {planet}_R5, tau);"
        )
    lines.extend([
        "            default: throw new IllegalArgumentException(\"Unsupported planet \" + planet);",
        "        }",
        "    }",
        "",
        "    static double[] earthCoordinates(double tau) {",
        "        return computeLBR("
        "EARTH_L0, EARTH_L1, EARTH_L2, EARTH_L3, EARTH_L4, EARTH_L5, "
        "EARTH_B0, EARTH_B1, EARTH_B2, EARTH_B3, EARTH_B4, EARTH_B5, "
        "EARTH_R0, EARTH_R1, EARTH_R2, EARTH_R3, EARTH_R4, EARTH_R5, tau);",
        "    }",
        "",
        "    private static double[] computeLBR(",
        "            double[][] l0, double[][] l1, double[][] l2, double[][] l3, double[][] l4, double[][] l5,",
        "            double[][] b0, double[][] b1, double[][] b2, double[][] b3, double[][] b4, double[][] b5,",
        "            double[][] r0, double[][] r1, double[][] r2, double[][] r3, double[][] r4, double[][] r5,",
        "            double tau) {",
        "        double L = sumPowerSeries(tau, l0, l1, l2, l3, l4, l5);",
        "        double B = sumPowerSeries(tau, b0, b1, b2, b3, b4, b5);",
        "        double R = sumPowerSeries(tau, r0, r1, r2, r3, r4, r5);",
        "        return new double[]{L, B, R};",
        "    }",
        "",
        "    private static double sumPowerSeries(double tau, double[][]... series) {",
        "        double total = 0.0;",
        "        double tauPower = 1.0;",
        "        for (double[][] terms : series) {",
        "            double partial = 0.0;",
        "            for (double[] term : terms) {",
        "                partial += term[0] * Math.cos(term[1] + term[2] * tau);",
        "            }",
        "            total += partial * tauPower;",
        "            tauPower *= tau;",
        "        }",
        "        return total;",
        "    }",
        "}",
        "",
    ])

    OUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUT_FILE.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    return total_terms


def main():
    planets_data = {}
    grand_total = 0
    for planet, fname in PLANETS:
        path = download(fname)
        all_series = list(parse_file(path))
        truncated = {}
        original_count = 0
        retained_count = 0
        for var, power, terms in all_series:
            original_count += len(terms)
            kept = truncate(var, terms)
            retained_count += len(kept)
            truncated.setdefault(var, {})[power] = kept
        print(f"  {planet}: {original_count} -> {retained_count} terms")
        planets_data[planet] = truncated
        grand_total += retained_count
    total_in_java = emit_java(planets_data)
    print(f"Wrote {OUT_FILE}")
    print(f"Total retained: {grand_total} (Java arrays count: {total_in_java})")
    if grand_total != total_in_java:
        raise SystemExit("Term count mismatch between in-memory and emitted Java")


if __name__ == "__main__":
    main()
